name: Deploy Production

on:
  workflow_run:
    workflows:
      - Publish Docker Image
    types:
      - completed

permissions:
  contents: read

jobs:

  deploy:

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    environment: production

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yml
          
          sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.event.workflow_run.head_sha }}|g" k8s/deployment.yml
          
          kubectl apply -f k8s/deployment.yml

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/appointment-scheduling -n appointments-prod